name: 5647Final
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2025.10.5
  - conda-pack=0.8.0
  - libcxx=20.1.8
  - libffi=3.4.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.4
  - python=3.8.20
  - readline=8.3
  - setuptools=75.1.0
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.44.0
  - xz=5.6.4
  - zlib=1.3.1
  - pip=23.2.1
  - pip:
      - absl-py==2.3.1
      - antlr4-python3-runtime==4.8
      - audioread==3.0.1
      - bitarray==3.7.1
      - cachetools==5.5.2
      - certifi==2025.10.5
      - cffi==1.17.1
      - charset-normalizer==3.4.3
      - colorama==0.4.6
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==3.1.4
      - decorator==5.2.1
      - fairseq==0.12.2
      - filelock==3.16.1
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - google-auth==2.41.1
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - hydra-core==1.0.7
      - idna==3.10
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - jinja2==3.1.6
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - librosa==0.9.1
      - llvmlite==0.41.1
      - loguru==0.7.3
      - lxml==6.0.2
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mpmath==1.3.0
      - networkx==3.1
      - numba==0.58.1
      - numpy==1.23.5
      - oauthlib==3.3.1
      - omegaconf==2.0.6
      - packaging==25.0
      - pillow==10.4.0
      - platformdirs==4.3.6
      - pooch==1.8.2
      - portalocker==3.0.0
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydub==0.25.1
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pyworld==0.3.4
      - pyyaml==6.0.3
      - regex==2024.11.6
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - resampy==0.4.3
      - rsa==4.9.1
      - sacrebleu==2.5.1
      - scikit-learn==1.3.2
      - scipy==1.10.0
      - six==1.17.0
      - soundfile==0.12.1
      - sympy==1.13.3
      - tabulate==0.9.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.5.0
      - torch==2.1.0
      - torchaudio==2.1.0
      - tqdm==4.67.1
      - typing-extensions==4.13.2
      - urllib3==2.2.3
      - werkzeug==3.0.6
      - zipp==3.20.2
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/5647Final
